wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.5
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718240331.0
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.12.3
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Epoch
      5: 1
      6:
      - 1
    - 1: Valid Loss
      5: 1
      6:
      - 1
    - 1: Valid Acc
      5: 1
      6:
      - 1
    - 1: Elapsed time
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid_loss_step
      5: 1
      6:
      - 1
    - 1: valid_acc_step
      5: 1
      6:
      - 1
    - 1: valid_loss_epoch
      5: 1
      6:
      - 1
    - 1: valid_acc_epoch
      5: 1
      6:
      - 1
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: valid_acc
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: test_loss_step
      5: 1
      6:
      - 1
    - 1: test_acc_step
      5: 1
      6:
      - 1
